name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Add GitHub
      run: dotnet nuget add source --username flx-team --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/flx-team/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack -c Release --no-restore
    - name: Publish
      run: dotnet nuget push ./Sources/**/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate --no-symbols 1 
